## Training the Final Chess Data with DecisionTree, RandomForest and XGBoost

In [19]:
import os
import pandas as pd
import numpy as np
import joblib
import sklearn
from sklearn.metrics import confusion_matrix, classification_report

#### Loading the Data

In [8]:
project_dir = os.path.dirname(os.getcwd())
games = pd.read_csv(os.path.join(project_dir,"data/final_chess.csv"))

In [10]:
games

,Site,Date,White,Black,Result,WhiteElo,BlackElo,ECO,EloDiff,AvgElo,...,h2h_WinDiff,h2h_WinRateDiff,DaysSinceLastGameDiff,ECO_Games,ECO_WhiteWin,ECO_BlackWin,ECO_Draw,ECO_WhiteWinRate,ECO_BlackWinRate,ECO_DrawRate
0,Talcahuano CHI,2012-06-02,"Caceres Leal,Jaime","Farfan Ortiz,V",0.5,2137.0,2206.0,D13,-69.0,2171.5,...,0,0.0,0,0,0,0,0,0.000000,0.000000,0.000000
1,Talcahuano CHI,2012-06-02,"Caceres Leal,Jaime","Salinas Herrera,P",0.0,2137.0,2409.0,A46,-272.0,2273.0,...,0,0.0,0,0,0,0,0,0.000000,0.000000,0.000000
2,Talcahuano CHI,2012-06-02,"Farfan Ortiz,E","Vizama Riveros,C",0.0,2236.0,2256.0,C42,-20.0,2246.0,...,0,0.0,0,0,0,0,0,0.000000,0.000000,0.000000
3,Talcahuano CHI,2012-06-02,"Rojas Sepulveda,E","Diaz Vasquez,M",0.5,2315.0,2212.0,A46,103.0,2263.5,...,0,0.0,0,1,0,1,0,0.000000,1.000000,0.000000
4,Talcahuano CHI,2012-06-02,"Estay Torreblanca,O","Alarcon,Rod",1.0,2214.0,2174.0,C17,40.0,2194.0,...,0,0.0,0,0,0,0,0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3255651,Aktobe KAZ,2026-06-08,"Kabinazar,Nurmukhammed","Tarhan,Adar",0.5,2312.0,2482.0,B11,-170.0,2397.0,...,0,0.0,0,8963,3442,3250,2271,0.384023,0.362602,0.253375
3255652,Aktobe KAZ,2026-06-08,"Zhalmakhanov,Ramazan","Kornienko,Konstantin",0.0,2478.0,2388.0,B28,90.0,2433.0,...,0,0.0,0,9793,3964,3997,1832,0.404779,0.408149,0.187072
3255653,Aktobe KAZ,2026-06-08,"Dronavalli,Harika","Degenbaev,Aziz",0.5,2466.0,2320.0,A06,146.0,2393.0,...,0,0.0,0,20988,9639,6895,4454,0.459262,0.328521,0.212217
3255654,Aktobe KAZ,2026-06-08,"Rozum,I","Makhnev,Denis",1.0,2455.0,2551.0,A40,-96.0,2503.0,...,0,0.0,0,45159,19568,17785,7806,0.433313,0.393831,0.172856
3255655,Acqui Terme ITA,2026-06-08,"Parvulescu,Nicu","Breggia Bicchiere,Antonio",1.0,1768.0,1698.0,B12,70.0,1733.0,...,0,0.0,0,48144,21088,17490,9566,0.438019,0.363285,0.198696

#### Converting the Data for Training

In [ ]:
X = games.drop(columns=["White", "Black", "Result", "Date", "Site", "ECO"])
y = games["Result"].map({1: 2, 0.5: 1, 0:0}) #sklearn only considers integers 

"""
0 = Black win
1 = Draw
2 = White win
"""

In [43]:
n = len(games)
s1 = int(0.7 * n)
s2 = int(0.85 * n)

In [44]:
X_train = X.iloc[:s1]
y_train = y.iloc[:s1]
X_val = X.iloc[s1:s2]
y_val = y.iloc[s1:s2]
X_test = X.iloc[s2:]
y_test = y.iloc[s2:]

#### Decision Tree

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
dtc = DecisionTreeClassifier()

In [47]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [48]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [58]:
y_pred = dtc.predict(X_val)
y_pred = dtc.predict(X_test)

In [59]:
confusion_matrix(y_test, y_pred)

array([[ 85081,  33681,  61682],
       [ 31858,  27758,  35428],
       [ 64349,  39647, 108865]])

In [61]:
classification_report(y_test, y_pred).splitlines()

['              precision    recall  f1-score   support',
 '',
 '           0       0.47      0.47      0.47    180444',
 '           1       0.27      0.29      0.28     95044',
 '           2       0.53      0.51      0.52    212861',
 '',
 '    accuracy                           0.45    488349',
 '   macro avg       0.42      0.43      0.42    488349',
 'weighted avg       0.46      0.45      0.46    488349']

In [62]:
X.columns

Index(['WhiteElo', 'BlackElo', 'EloDiff', 'AvgElo', 'HigherRatedPlayer',
       'WhiteGames', 'WhiteWin', 'WhiteLoss', 'WhiteDraw', 'BlackGames',
       'BlackWin', 'BlackLoss', 'BlackDraw', 'WhiteWinRate', 'WhiteLossRate',
       'WhiteDrawRate', 'BlackWinRate', 'BlackLossRate', 'BlackDrawRate',
       'WLast10', 'BLast10', 'WasWGames', 'WasWWin', 'WasWLoss', 'WasWDraw',
       'WasBGames', 'WasBWin', 'WasBLoss', 'WasBDraw', 'BasWGames', 'BasWWin',
       'BasWLoss', 'BasWDraw', 'BasBGames', 'BasBWin', 'BasBLoss', 'BasBDraw',
       'WasWWinRate', 'WasWLossRate', 'WasWDrawRate', 'WasBWinRate',
       'WasBLossRate', 'WasBDrawRate', 'BasWWinRate', 'BasWLossRate',
       'BasWDrawRate', 'BasBWinRate', 'BasBLossRate', 'BasBDrawRate',
       'h2h_games', 'h2h_Player1Win', 'h2h_Player2Win', 'h2h_Draw',
       'h2h_Player1WinRate', 'h2h_Player2WinRate', 'h2h_DrawRate', 'h2h_last5',
       'WhiteDaysSinceLastGame', 'BlackDaysSinceLastGame', 'Last10Diff',
       'GamesDiff', 'WinDiff', 'WinRateDiff', 'h2h_WinDiff', 'h2h_WinRateDiff',
       'DaysSinceLastGameDiff', 'ECO_Games', 'ECO_WhiteWin', 'ECO_BlackWin',
       'ECO_Draw', 'ECO_WhiteWinRate', 'ECO_BlackWinRate', 'ECO_DrawRate'],
      dtype='str')

In [76]:
pd.DataFrame(dtc.feature_importances_, index=X.columns).sort_values(by=0).head(50)

                               0
HigherRatedPlayer       0.000107
h2h_Draw                0.001110
h2h_Player1Win          0.001136
h2h_Player2Win          0.001165
h2h_Player2WinRate      0.001597
h2h_Player1WinRate      0.001651
h2h_WinDiff             0.001987
h2h_WinRateDiff         0.002217
h2h_games               0.002615
h2h_DrawRate            0.002708
h2h_last5               0.003006
WhiteGames              0.005862
WhiteWin                0.005866
BlackGames              0.005957
BlackWin                0.005994
WasBGames               0.006003
WasWGames               0.006139
BasWGames               0.006155
BasBGames               0.006196
WhiteDraw               0.006248
BlackDraw               0.006442
BasWWin                 0.006629
BasBWin                 0.006641
WasBWin                 0.006663
WasWWin                 0.006718
WasBDraw                0.006843
WasWDraw                0.006943
BasBDraw                0.007074
DaysSinceLastGameDiff   0.007091
BasWDraw                0.007144
BlackLoss               0.007404
WhiteLoss               0.007496
WasBLoss                0.007769
BasBLoss                0.007779
WhiteDaysSinceLastGame  0.007831
WasWLoss                0.007982
BasWLoss                0.008466
WinDiff                 0.012021
ECO_Games               0.012148
BLast10                 0.013115
WLast10                 0.013156
BlackDaysSinceLastGame  0.013455
GamesDiff               0.013683
AvgElo                  0.014196
BlackWinRate            0.014441
WhiteWinRate            0.014617
ECO_WhiteWin            0.014788
ECO_BlackWin            0.015828
Last10Diff              0.016050
BlackElo                0.016423